### ISSUE TITLE
More infos about GEN8 chunk

### ISSUE THREAD

**Issue by minirop** [panzi/cook-serve-hoomans3#1]
Hello,
during my own research about decompiling GM:S games, I found [GMiner](https://github.com/jmazzola/GMiner), which seems to have understood all the field in the GEN8 chunk of GM:S 1. [See form1.cs](https://github.com/jmazzola/GMiner/blob/master/GMiner/Form1.cs#L80)

Also, you can notice the field `flags` which can contains `StudioEdition_EqualsX` telling which version was used (at least the minor field).

**Comment by panzi** [comment]
Interesting. Thank you! Though there is no issue, is there?

**Comment by minirop** [comment]
no issues, just found that using that channel to contact you was the easier/faster way.
